error: rename pkgcraft_free_str() to pkgcraft_str_free()
And have it accept a NonNull<c_char> to match other `free` functions.

Also, return *mut c_char from string functions instead of *const c_char.

This simplifies the free function and in addition cgo has no concept of
const modifiers for pointers anyway.